apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: default
  labels:
    release: monitors
spec:
  route:
    repeatInterval: 30m
    receiver: 'null'
    routes:
    - matchers:
      - name: alertname
        value: HighCpuUsage
      receiver: 'send-email'
    - matchers:
      - name: alertname
        value: PodRestart
      receiver: 'send-email'
      repeatInterval: 5m
  receivers:
  - name: 'send-email'
    emailConfigs:
    - to: GMAIL_HERE
      from: GMAIL_HERE
      sendResolved: false
      smarthost: smtp.gmail.com:587
      authUsername: GMAIL_HERE
      authIdentity: GMAIL_HERE
      authPassword:
        name: mail-pass
        key: gmail-pass
  - name: 'null'
